server:
  port: 8080

spring:
  application:
    name: bankcards

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/bankcards}
    username: ${SPRING_DATASOURCE_USERNAME:bankcards}
    password: ${SPRING_DATASOURCE_PASSWORD:bankcards}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/migration/db.changelog-master.yaml

jwt:
  secret: ${JWT_SECRET}
  expiration-ms: ${JWT_EXPIRATION_MS:86400000}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
